-- ============================================================================
-- Leviio — Client portal approval gate
-- ----------------------------------------------------------------------------
-- NO MIGRATION REQUIRED.
--
-- The client's portal access state ('none' -> 'pending' -> 'approved') is now
-- stored inside the existing clients.metrics jsonb column, so there is nothing
-- to run here. Adding/saving clients works on the base schema as-is.
--
-- If you previously ran an older version of this file that added a
-- `portal_status` COLUMN, it's harmless to leave it — the app ignores it. To
-- remove it (optional cleanup):
--
--   alter table public.clients drop constraint if exists clients_portal_status_check;
--   alter table public.clients drop column if exists portal_status;
-- ============================================================================
